# Generated by Django 4.2 on 2023-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
        migrations.AddField(
            model_name='movie',
            name='description2',
            field=models.TextField(default='3', verbose_name='Ссылка:'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default=1, upload_to='videos/', verbose_name='Видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='MovieShots',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
